Jahia/site-settings-seo

jahia.json, package.json, src/javascript/register.js, src/main/resources/javascript/locales/en.json, webpack.config.js, yarn.lock
https://jira.jahia.org/browse/PROJECT-XXX
=> BACKLOG-12272: Added vanity urls to additional accordion

src/javascript/register.js
https://jira.jahia.org/browse/PROJECT-XXX
=> BACKLOG-12877: Fixed links

src/javascript/register.js
https://jira.jahia.org/browse/BACKLOG-12942
Updated position priority in the additional accordion
=> BACKLOG-12942: updated position in the additional accordion

src/main/resources/javascript/locales/de.json, src/main/resources/javascript/locales/en.json
https://jira.jahia.org/browse/BACKLOG-12941
Fixed label in site settings
=> BACKLOG-12941: Fixed labels in site settings

src/javascript/register.js
https://jira.jahia.org/browse/BACKLOG-13102
Added the icon for vanity url dashboard in the additional accordion
=> BACKLOG-13102: added icon for vanity url dashboard in nav

LICENSE.txt, pom.xml, src/main/resources/META-INF/LICENSE.txt, src/main/resources/javascript/locales/de.json, src/main/resources/javascript/locales/en.json, src/main/resources/javascript/locales/fr.json
https://jira.jahia.org/browse/BACKLOG-12284
POM updated to be compatible with the upcoming v8. So I've updated the versions (module and parent), added a signature and the copyright
=> [BACKLOG-12284] Update versions, copyright and add signature for v8

.circleci/.circleci.settings.xml
https://jira.jahia.org/browse/BACKLOG-15753
=> BACKLOG-15753 - Add owasp plugin

src/main/resources/META-INF/jahia-content-editor-forms/fieldsets/jmix_description_move_section.json
https://jira.jahia.org/browse/BACKLOG-15732
Move description field from Metadata section to SEO using JSON overrides
=> BACKLOG-15732: Move description field from Metadata to SEO

pom.xml, src/main/java/org/jahia/modules/sitesettingsseo/SeoUrlFilter.java
https://jira.jahia.org/browse/BACKLOG-15553
Inject canonical and alternate urls in the head of the page
=> Backlog 15553 canonical url

pom.xml
https://jira.jahia.org/browse/BACKLOG-15842
Update parent pom to use 8.0.3
=> BACKLOG-15842: Updated parent to 8.0.3.0-SNAPSHOT

src/javascript/components/VanityMutationsProvider.jsx, src/javascript/components/VanityUrlList.jsx, src/javascript/components/VanityUrlTableView.jsx
https://jira.jahia.org/browse/BACKLOG-15892
Fix context refresh issue
=> Backlog 15892 refresh issue

src/main/resources/javascript/locales/de.json
https://jira.jahia.org/browse/BACKLOG-15932
Added german translation
=> BACKLOG-15932: add german translation

src/main/resources/javascript/locales/fr.json
https://jira.jahia.org/browse/BACKLOG-15932
Added translation for french
=> BACKLOG-15932: update fr.json

src/main/resources/javascript/locales/de.json
https://jira.jahia.org/browse/BACKLOG-15932
Insert comma
=> BACKLOG-15932 Insert comma

src/main/java/org/jahia/modules/sitesettingsseo/SeoUrlFilter.java
https://jira.jahia.org/browse/BACKLOG-15911
Changing from using underscore to dash on hreflang
=> BACKLOG-15911: Change from underscore to dash.

src/main/resources/javascript/locales/en.json, src/main/resources/javascript/locales/fr.json
https://jira.jahia.org/browse/BACKLOG-15914
Trivial changes on label text.
=> BACKLOG-15914: Trivial text change on labels.

src/main/java/org/jahia/modules/sitesettingsseo/SeoUrlFilter.java
https://jira.jahia.org/browse/BACKLOG-16136
Add c:url implementation (which is basically a call to `response.encodeURL()`) on the node path to accommodate URL rewrite rules
=> BACKLOG-16136: Implement c:url to accommodate URL rewrite rules in canonical URLs

yarn.lock
https://jira.jahia.org/browse/BACKLOG-16271
=> BACKLOG-16271 : js lib upgrade

LICENSE, pom.xml, src/main/java/org/jahia/modules/sitesettingsseo/SeoUrlFilter.java, src/main/java/org/jahia/modules/sitesettingsseo/utils/Utils.java
https://jira.jahia.org/browse/QA-14203
=> QA-14203 - Update copyright year and license header

src/javascript/components/Move.jsx
https://jira.jahia.org/browse/BACKLOG-17092
fixed by adding  error-policy
=> BACKLOG-17092: use functional component, add error-policy

src/javascript/components/Deletion.jsx, src/javascript/components/Editable.jsx, src/javascript/components/Move.jsx, src/javascript/components/Publication.jsx, src/javascript/components/Selection.jsx, src/javascript/components/contentEditor/actions/VanityAction.jsx
https://jira.jahia.org/browse/BACKLOG-17170
=> BACKLOG-17170: Fixed compatibility

src/javascript/components/contentEditor/actions/VanityAction.jsx
https://jira.jahia.org/browse/BACKLOG-17074
Improve error message to be able to tell what's going on
=> BACKLOG-17074 Produce a legible message in case of import error

pom.xml
https://jira.jahia.org/browse/BACKLOG-17301
Signature update
=> BACKLOG-17301 Change signature

src/javascript/components/SiteSettingsSeoApp.jsx
https://jira.jahia.org/browse/BACKLOG-16244
=> BACKLOG-16244 : fix error message in app

pom.xml
=> BACKLOG-16244 : set minimum jahia version

src/javascript/components/VanityUrlTableData.jsx
https://jira.jahia.org/browse/BACKLOG-17101
=> Backlog 17101 fix issue

.github/dependabot.yml, .github/workflows/on-code-change.yml, .github/workflows/on-merge.yml, .github/workflows/on-release.yml, .github/workflows/on-rollback.yml, .github/workflows/schedule-sonar.yml, yarn.lock
=> BACKLOG-17247: Updated vulnerabilities

src/javascript/components/VanityUrlList.jsx
https://jira.jahia.org/browse/QA-14288
=> QA-14288: Fix Vanity URL dashboard: staging and live table not aligned.

src/main/resources/javascript/locales/en.json, src/main/resources/javascript/locales/fr.json, src/main/resources/resources/site-settings-seo_en.properties
https://jira.jahia.org/browse/BACKLOG-16475
=> BACKLOG-16475 - Vanity URLs labels

src/main/resources/javascript/locales/fr.json
https://jira.jahia.org/browse/BACKLOG-20596
=> BACKLOG-20596: Fix typo in vanity urls in French.

src/main/java/org/jahia/modules/sitesettingsseo/SeoUrlFilter.java
https://jira.jahia.org/browse/QA-14674
=> QA-14674: Fix missing alternate urls.

src/main/resources/javascript/locales/de.json, src/main/resources/javascript/locales/en.json, src/main/resources/javascript/locales/fr.json
https://jira.jahia.org/browse/BACKLOG-20596
=> BACKLOG-20596: Fix some typo and update copyright

src/main/resources/javascript/locales/de.json
https://jira.jahia.org/browse/BACKLOG-20583
=> BACKLOG-20583: Fix some typo in german

core/src/javascript/components/LanguageSelector/LanguageSelector.jsx
https://jira.jahia.org/browse/BACKLOG-16875
=> BACKLOG-16875 : fix site switching

core/src/javascript/components/VanityList/DefaultRow.scss
https://jira.jahia.org/browse/BACKLOG-20605
=> BACKLOG-20605: Fix color issue with vanity url marked for deletion

core/src/javascript/components/VanityList/DefaultRow.jsx, core/src/javascript/components/VanityList/DefaultRow.scss
https://jira.jahia.org/browse/BACKLOG-20605
=> BACKLOG-20605: Align colors status with jContent

core/src/javascript/components/VanityList/DefaultRow.jsx, core/src/javascript/components/VanityList/DefaultRow.scss, core/src/javascript/components/VanityList/VanityUrlListDefault.jsx, core/src/javascript/components/VanityList/VanityUrlListDefault.scss
https://jira.jahia.org/browse/BACKLOG-20618
=> BACKLOG-20618: Fix display issues when first row is a moved vanity url.

.github/workflows/nightly.yml, .github/workflows/on-code-change.yml, .github/workflows/on-merge.yml, tests/docker-compose.yml
Cypress was present but there was nothing to trigger its execution.
=> BACKLOG-20594: Added missing CI/CD config for execution tests

core/package.json, core/src/javascript/components/SiteSettingsSeoApp.jsx, core/src/javascript/components/contentEditor/SiteSettingsSeo/SiteSettingsSeoCardApp.jsx, core/src/javascript/components/contentEditor/SiteSettingsSeo/SiteSettingsSeoCardApp.scss, core/yarn.lock
https://jira.jahia.org/browse/BACKLOG-20630
=> BACKLOG-20630: Fix wrong size of dropdown after changes in moonstone.

core/pom.xml, core/src/main/import/repository.xml
https://jira.jahia.org/browse/TECH-1092
Site setting seo, register in jcontent and uses only graphql. So no need for default or site settings dependencies
=> TECH-1092: remove default, sitesettings. add jcontent

core/src/main/resources/META-INF/patches/3.6.0-siteSettingsSeo.started.groovy
https://jira.jahia.org/browse/BACKLOG-20617
=> BACKLOG-20617 : migration of old vanity when starting the module

core/src/javascript/components/AddVanityUrl.jsx
https://jira.jahia.org/browse/BACKLOG-20678
=> BACKLOG-20678: Fix save button alignment for all language

core/src/javascript/components/Utils/Utils.jsx
https://jira.jahia.org/browse/BACKLOG-20681
=> BACKLOg-20681 : fix property reading error

core/src/javascript/components/VanityList/DefaultRow.jsx
https://jira.jahia.org/browse/BACKLOG-20681
=> BACKLOG-20681 : handle conflict status

core/src/javascript/components/VanityList/DefaultRow.scss
https://jira.jahia.org/browse/BACKLOG-20706
=> BACKLOG-20706: Fixed issue to not depend on jContent css variables

core/src/javascript/components/SiteSettingsSeoWrapper.jsx
see https://jira.jahia.org/browse/BACKLOG-20716
=> BACKLOG-20716 : fix site switching issue with jahia 8.1.0.0

core/package.json
https://jira.jahia.org/browse/QA-14754
=> QA-14754: Update module package version

core/webpack.config.js
https://jira.jahia.org/browse/QA-14754
=> QA-14754: Fix cache issue

tests/provisioning-manifest-snapshot.yml
https://jira.jahia.org/browse/BACKLOG-20770
=> BACKLOG-20770: Fix nightly tests

yarn.lock
https://jira.jahia.org/browse/BACKLOG-20791
Issue with yarn.lock during release
=> BACKLOG-20791: Fix yarn.lock file

src/main/java/org/jahia/modules/sitesettingsseo/SeoUrlFilter.java, tests/cypress/e2e/multilang.site.test.cy.ts, tests/cypress/e2e/singlelang.site.test.cy.ts, tests/jahia-module/pom.xml, tests/yarn.lock
https://jira.jahia.org/browse/QA-14839
=> QA-14839: Alternate tag should not exist for single language site

tests/cypress/e2e/edit/checkToolbarVanityUrlsPageUi.cy.ts, tests/cypress/e2e/edit/checkToolbarVanityYrlsPageUi.cy.ts, tests/cypress/page-object/vanityUrls.page.ts
https://jira.jahia.org/browse/QA-14916
=> QA-14916: Add cypress to test Toolbar comportment

src/main/import/roles.xml
https://jira.jahia.org/browse/BACKLOG-21587
=> BACKLOG-21278 : remove wrong attribute on editor role definition

.github/workflows/on-code-change.yml, .github/workflows/on-merge.yml, .github/workflows/on-release.yml, pom.xml, tests/jahia-module/pom.xml
https://jira.jahia.org/browse/QA 14836
=> QA 14836: Fix worng version on 4x branch

src/javascript/components/actions/VanityAction.jsx, src/main/resources/resources/site-settings-seo_de.properties, src/main/resources/resources/site-settings-seo_en.properties, src/main/resources/resources/site-settings-seo_fr.properties, tests/cypress/e2e/permissions/checkUisPermissions.cy.ts, tests/cypress/page-object/ContentEditorSEO.ts
https://jira.jahia.org/browse/BACKLOG-21626
=> BACKLOG-21626: Backport

pom.xml
https://jira.jahia.org/browse/BACKLOG-21585
=> BACKLOG-21585: Upgrade parent version to 8.1.3.0

package.json, src/javascript/components/Context/VanityUrl.context.jsx, src/javascript/components/LanguageMenu.jsx, src/javascript/components/LanguageSelector/LanguageSelector.jsx, yarn.lock
https://jira.jahia.org/browse/BACKLOG-20677
=> BACKLOG-20677: Use UI language for language menus

src/javascript/components/AddVanityUrl.jsx, src/javascript/components/VanityList/DefaultRow.jsx
https://jira.jahia.org/browse/BACKLOG-21818
Prevent `:*?"<>|%` chars and URLs ending with .do
=> BACKLOG-21818: prevent forbidden url

src/javascript/components/AddVanityUrl.jsx, src/javascript/components/VanityList/DefaultRow.jsx, src/main/resources/javascript/locales/de.json, src/main/resources/javascript/locales/en.json, src/main/resources/javascript/locales/fr.json, tests/cypress.config.ts, tests/cypress/e2e/edit/addVanityUrlUi.cy.ts, tests/cypress/page-object/VanityUrlUi.ts
https://jira.jahia.org/browse/[BACKLOG-21818](https://github.com/Jahia/site-settings-seo/commit/2e2796948c0710c14c996763895d511868fe9be3)
=> BACKLOG-21818

package.json, src/javascript/components/Register/registerActions.js, src/javascript/components/actions/VanityAction.jsx, yarn.lock
https://jira.jahia.org/browse/QA-15005
Hide entry menu for vanity urls when node is external
=> QA-15005: Hide vanity urls on external node

.github/maven.settings.xml
https://jira.jahia.org/browse/BACKLOG-22187
=> BACKLOG-22187: add server in maven settings to release test module

src/javascript/components/Move.jsx
https://jira.jahia.org/browse/BACKLOG-22208
Check if Picker is present before setting the value of the open path on move
=> BACKLOG-22208: check ref current exists before accessing to it

src/javascript/components/AddVanityUrl.jsx, tests/cypress/e2e/edit/addVanityUrlUi.cy.ts, tests/cypress/page-object/VanityUrlUi.ts
https://jira.jahia.org/browse/BACKLOG-22226
=> BACKLOG-22226: fix on blur on vanity url creation

pom.xml, src/javascript/components/SiteSettingsSeoApp.jsx, src/javascript/components/VanityUrlTableData.jsx, tests/cypress/e2e/dashboard/checkPagination.test.cy.ts, tests/cypress/page-object/dashboard/PageWithVanityUrlList.ts, tests/cypress/page-object/dashboard/Pagination.ts, tests/cypress/page-object/vanityUrls.page.ts
https://jira.jahia.org/browse/BACKLOG-21190
Wait that the results are fully loaded when getting the pages with vanity url before displaying them
=> BACKLOG-21190: fix pagination

.github/workflows/nightly-rl.yml, .github/workflows/nightly-sn.yml, .github/workflows/on-code-change.yml, .github/workflows/on-merge.yml, tests/provisioning-manifest-build.yml, tests/provisioning-manifest-snapshot.yml
https://jira.jahia.org/browse/TECH-1408
=> TECH-1408: Re enabled tests on jahia release and fixed provisioning

tests/jahia-module/pom.xml
https://jira.jahia.org/browse/BACKLOG-22964
=> BACKLOG-22964: upgrade jahia parent version

src/javascript/components/Register/registerActions.js, src/javascript/components/Utils/Utils.jsx, src/javascript/components/VanityList/DefaultRow.jsx, src/javascript/components/actions/MoveVanityAction.jsx, src/javascript/components/actions/PublishAllAction.jsx, src/javascript/components/actions/PublishVanityAction.jsx, src/javascript/components/actions/UpdateVanityAction.jsx, src/javascript/components/contentEditor/SiteSettingsSeo/SiteSettingsSeoCardApp.jsx, src/javascript/components/gqlFragments.js, src/javascript/components/gqlQueries.js, src/main/resources/javascript/locales/de.json, src/main/resources/javascript/locales/en.json, src/main/resources/javascript/locales/fr.json, tests/cypress/e2e/permissions/checkPublicationPermissions.cy.ts, tests/cypress/page-object/components/Menu.ts, tests/cypress/page-object/components/PageCard.ts, tests/cypress/page-object/components/VanityUrlRow.ts
https://jira.jahia.org/browse/QA-15061
=> QA-15061: only display request publication if necessary

src/javascript/components/Register/registerActions.js, src/javascript/components/Utils/Utils.jsx, src/javascript/components/VanityList/DefaultRow.jsx, src/javascript/components/actions/MoveVanityAction.jsx, src/javascript/components/actions/PublishAllAction.jsx, src/javascript/components/actions/PublishVanityAction.jsx, src/javascript/components/actions/UpdateVanityAction.jsx, src/javascript/components/contentEditor/SiteSettingsSeo/SiteSettingsSeoCardApp.jsx, src/javascript/components/gqlFragments.js, src/javascript/components/gqlQueries.js, src/main/resources/javascript/locales/de.json, src/main/resources/javascript/locales/en.json, src/main/resources/javascript/locales/fr.json, tests/cypress/e2e/permissions/checkPublicationPermissions.cy.ts, tests/cypress/page-object/components/Menu.ts, tests/cypress/page-object/components/PageCard.ts, tests/cypress/page-object/components/VanityUrlRow.ts
https://jira.jahia.org/browse/QA-15061
=> QA-15061: only display request publication if necessary 

.github/workflows/nightly-rl.yml, .github/workflows/nightly-sn.yml, .github/workflows/on-code-change.yml, .github/workflows/on-merge.yml, .github/workflows/on-release.yml, .github/workflows/on-rollback.yml, .github/workflows/schedule-sonar.yml
https://jira.jahia.org/browse/TECH-1639
upgrade actions
=> TECH-1639 upgrade actions

src/javascript/components/Register/registerActions.js, src/javascript/components/Toolbar/Toolbar.jsx, src/javascript/components/Utils/Utils.jsx, src/javascript/components/VanityList/DefaultRow.jsx, src/javascript/components/actions/PublishAllAction.jsx, src/javascript/components/actions/UnpublishVanityAction.jsx, tests/cypress/e2e/actions/checkUnpublishActions.cy.ts, tests/cypress/e2e/publication/checkPublicationButtons.cy.ts, tests/cypress/e2e/publication/checkUnpublication.cy.ts, tests/cypress/page-object/components/Menu.ts
https://jira.jahia.org/browse/QA-15066
=> QA-15066: add unpublish action on vanity urls (#221)

src/javascript/components/Publication/Publication.jsx, src/javascript/components/VanityList/DefaultRow.jsx, tests/cypress/e2e/delete/checkDeleteAction.cy.ts, tests/cypress/page-object/components/Menu.ts, tests/cypress/page-object/components/VanityUrlRow.ts, tests/cypress/page-object/components/dialog/PublicationValidationDialog.ts, tests/cypress/page-object/dashboard/Toolbar.ts, tests/cypress/utils/Utils.ts
https://jira.jahia.org/browse/BACKLOG-23048
=> BACKLOG-23048: add test on deletion

tests/cypress/e2e/delete/checkDeletePermanentlyAction.cy.ts, tests/cypress/page-object/components/Menu.ts
https://jira.jahia.org/browse/BACKLOG-23047
=> BACKLOG-23047: add tests on delete buttons

src/main/resources/META-INF/migration/migration-script.groovy
https://jira.jahia.org/browse/QA-15171
=> QA-15171: sort by uuid to avoid order issue in migration script

src/javascript/components/AddVanityUrl/AddVanityUrl.scss
https://jira.jahia.org/browse/BACKLOG-23064
=> BACKLOG-23064: fix style for add vanity url row

src/javascript/components/AddVanityUrl/AddVanityUrl.jsx, src/javascript/components/Move/MoveValidationDialog.jsx, src/javascript/components/SiteSettingsSeoApp.constants.js, src/javascript/components/SiteSettingsSeoApp.jsx, src/javascript/components/VanityList/DefaultRow.jsx, src/javascript/components/VanityUrlTableData.jsx, src/javascript/components/actions/MoveVanityAction.jsx, src/javascript/components/contentEditor/SiteSettingsSeo/SiteSettingsSeoCardApp.jsx
https://jira.jahia.org/browse/BACKLOG-23049
Remove loading part to not reload totally the page once the language selection changed
=> BACKLOG-23049: avoid useless reload

src/javascript/components/AddVanityUrl/AddVanityUrl.jsx, src/javascript/components/VanityUrlTableData.jsx, tests/cypress/e2e/publication/checkUnpublication.cy.ts, tests/package.json, tests/provisioning-manifest-snapshot.yml, tests/yarn.lock
https://jira.jahia.org/browse/BACKLOG-23080
=> BACKLOG-23080: fix broken tests

src/javascript/components/VanityList/DefaultRow.jsx, tests/cypress/e2e/edit/addVanityUrlUi.cy.ts, tests/cypress/page-object/ContentEditorSEO.ts, tests/cypress/page-object/components/AddVanityUrl.ts, tests/cypress/page-object/components/PageCard.ts, tests/cypress/page-object/components/VanityUrlRow.ts, tests/cypress/page-object/components/dialog/VanityUrlsDialog.ts, tests/cypress/page-object/dashboard/PageWithVanityUrlList.ts
https://jira.jahia.org/browse/BACKLOG-23052
=> BACKLOG-23052: clean test to avoid flakiness

src/javascript/components/SiteSettingsSeoApp.jsx, src/javascript/components/VanityUrlTableData.jsx, src/javascript/components/contentEditor/SiteSettingsSeo/SiteSettingsSeoCardApp.jsx
https://jira.jahia.org/browse/BACKLOG-23093
=> BACKLOG-23093: hide NoVanity component when data are loading

tests/env.debug.sh, tests/env.run.sh, tests/provisioning-manifest-snapshot.yml
- fix test by using released version of jcontent
- improve cypress debug mode
=> BACKLOG-23120 : fix cypress tests execution

src/main/resources/META-INF/definitions.cnd, src/main/resources/META-INF/jahia-content-editor-forms/forms/jmix_mainResource_rename_description.json, src/main/resources/META-INF/jahia-content-editor-forms/forms/jnt_page_rename_description.json, src/main/resources/resources/site-settings-seo_de.properties, src/main/resources/resources/site-settings-seo_en.properties, src/main/resources/resources/site-settings-seo_fr.properties
https://jira.jahia.org/browse/BACKLOG-23136
=> BACKLOG-23136: Add openGraphImage field to SEO section

tests/cypress/e2e/seoOverrides/definitions.cy.ts, tests/package.json, tests/yarn.lock
https://jira.jahia.org/browse/BACKLOG-23136
=> BACKLOG-23136: Add tests for new SEO fields

.github/workflows/manual-run.yml
https://jira.jahia.org/browse/BACKLOG-23237
=> BACKLOG-23237: Create manual-run.yml

tests/provisioning-manifest-release.yml
Updated the provisioning for nightly on release because we changed some data-sel attributes in jcontent so we need the latest jcontent for the tests to work.
=> TECH-1880: update provisioning

.github/workflows/manual-run.yml
=> Fix Testrail project name

src/javascript/components/VanityList/DefaultRow.jsx, src/javascript/components/VanityList/DefaultRow.scss
Update colors to match jContent
...
=> BACKLOG-23539: Update colors to match jContent

src/javascript/components/contentEditor/EditvanityUrlsDialog/EditVanityUrlsDialog.scss
=> QA-15404: Fixed styling for long dialog titles

tests/provisioning-manifest-release.yml
Update jcontent to latest 3.2.0 release inside provisioning
=> test: update jcontent to latest release inside provisioning

src/javascript/components/VanityUrlEnabledContent.jsx, tests/cypress/e2e/fields/seoKeywords.cy.ts
...
Update styles to wrap text in header
> [!TIP]
> Documentation to guide the reviews: [How to do a code review](https://jahia-confluence.atlassian.net/wiki/spaces/PR/pages/2064660/How+to+do+a+code+review+-+Ref+ISSOP08.A14006)
=> fix: Update styles to wrap text in header

src/javascript/components/AddVanityUrl/AddVanityUrl.jsx, src/javascript/components/VanityList/DefaultRow.jsx, tests/cypress/e2e/dashboard/editInDashboard.cy.ts, tests/package.json, tests/yarn.lock
Handle the case when a user types // in the vanity url input. An error message should be displayed.
> [!TIP]
> Documentation to guide the reviews: [How to do a code review](https://jahia-confluence.atlassian.net/wiki/spaces/PR/pages/2064660/How+to+do+a+code+review+-+Ref+ISSOP08.A14006)
=> fix: handle correctly the error when user type invalid characters
